import { createContext, useContext, useState, useCallback, useEffect } from 'react';
import { chatService } from '../services/chatService';

/* eslint-disable react-refresh/only-export-components */

const ChatbotContext = createContext(null);

export const ChatbotProvider = ({ children }) => {
  // UI State
  const [isOpen, setIsOpen] = useState(false);
  const [isMinimized, setIsMinimized] = useState(false);

  // Sessions State
  const [sessions, setSessions] = useState([]);
  const [sessionsLoading, setSessionsLoading] = useState(false);
  const [sessionsError, setSessionsError] = useState(null);
  
  // Current Conversation State
  const [activeSessionId, setActiveSessionId] = useState(null);
  const [messages, setMessages] = useState([]);
  const [messagesLoading, setMessagesLoading] = useState(false);
  const [messagesError, setMessagesError] = useState(null);
  
  // Message Sending State
  const [isSending, setIsSending] = useState(false);
  const [error, setError] = useState(null); // General error for sending

  // Fetch Sessions
  const fetchSessions = useCallback(async (page = 1, size = 20, silent = false) => {
    if (!silent) setSessionsLoading(true);
    setSessionsError(null);
    try {
      const data = await chatService.listChatSessions({ page, size });
      setSessions(data.items || []);
    } catch (_err) {
      setSessionsError('Failed to load chat history.');
    } finally {
      if (!silent) setSessionsLoading(false);
    }
  }, []);

  // Fetch Messages for a specific session
  const fetchMessages = useCallback(async (sessionId) => {
    setMessagesLoading(true);
    setMessagesError(null);
    try {
      const data = await chatService.getChatMessages(sessionId);
      setMessages(data.items || []);
    } catch (_err) {
      setMessagesError('Failed to load messages.');
    } finally {
      setMessagesLoading(false);
    }
  }, []);

  // Select a session from history
  const selectSession = useCallback((sessionId) => {
    setActiveSessionId(sessionId);
    setMessages([]); // Clear current
    fetchMessages(sessionId);
  }, [fetchMessages]);

  // Load initial history when chat is first opened
  const [hasLoadedHistory, setHasLoadedHistory] = useState(false);
  useEffect(() => {
    if (isOpen && !hasLoadedHistory) {
      fetchSessions();
      setHasLoadedHistory(true);
    }
  }, [isOpen, hasLoadedHistory, fetchSessions]);

  // UI Handlers
  const toggleChat = useCallback(() => {
    setIsOpen(prev => !prev);
    setIsMinimized(false);
  }, []);

  const closeChat = useCallback(() => {
    setIsOpen(false);
    setIsMinimized(false);
  }, []);

  const openChat = useCallback(() => {
    setIsOpen(true);
    setIsMinimized(false);
  }, []);

  const minimizeChat = useCallback(() => {
    setIsMinimized(true);
  }, []);

  const restoreChat = useCallback(() => {
    setIsMinimized(false);
  }, []);

  const handleNewChat = useCallback(() => {
    setActiveSessionId(null);
    setMessages([]);
    setError(null);
    setMessagesError(null);
  }, []);

  // Send Message
  const handleSend = useCallback(async (text) => {
    if (!text.trim()) return;
    setError(null);
    
    // Optimistic user message
    const optimisticUserMsg = { id: Date.now().toString(), role: 'user', content: text, created_at: new Date().toISOString() };
    setMessages((prev) => [...prev, optimisticUserMsg]);
    setIsSending(true);

    try {
      let currentSessionId = activeSessionId;
      let isFirstMessage = false;

      // Lazy Session Creation
      if (!currentSessionId) {
        const sessionData = await chatService.createChatSession();
        currentSessionId = sessionData.session_id;
        setActiveSessionId(currentSessionId);
        isFirstMessage = true;
      }

      // Send the actual message
      const response = await chatService.sendChatMessage(currentSessionId, text);
      
      const assistantMsg = { 
        id: Date.now().toString() + '-ai', 
        role: 'assistant', 
        content: response.answer, 
        question_type: response.question_type,
        created_at: new Date().toISOString()
      };
      
      setMessages((prev) => [...prev, assistantMsg]);

      // If this was the first message, refresh sessions to capture the generated title
      if (isFirstMessage) {
        // Immediate refresh to show the new session (even if title is default)
        fetchSessions(1, 20, true);
        // Delayed refresh to get the asynchronous title generated by backend
        setTimeout(() => {
          fetchSessions(1, 20, true);
        }, 3000);
      }

    } catch (_err) {
      setError('Failed to send message.');
    } finally {
      setIsSending(false);
    }
  }, [activeSessionId, fetchSessions]);

  const value = {
    isOpen,
    isMinimized,
    toggleChat,
    closeChat,
    openChat,
    minimizeChat,
    restoreChat,
    
    sessions,
    sessionsLoading,
    sessionsError,
    fetchSessions,
    
    activeSessionId,
    selectSession,
    
    messages,
    messagesLoading,
    messagesError,
    
    isGenerating: isSending,
    isSending,
    error,
    
    handleSend,
    handleNewChat,
    setError
  };

  return (
    <ChatbotContext.Provider value={value}>
      {children}
    </ChatbotContext.Provider>
  );
};

export const useChatbot = () => {
  const context = useContext(ChatbotContext);
  if (!context) {
    throw new Error('useChatbot must be used within a ChatbotProvider');
  }
  return context;
};
