name: CI Code Quality

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  check-code:
    name: Check unused code and imports
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.18.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (Check unused imports and variables)
        run: npx eslint . --max-warnings=0
